name: MLflow CI/CD Pipeline to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: 3. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas

      - name: 4. Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      - name: 5. Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(experiment_ids=['0']).iloc[0].run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Berhasil mendapatkan Run ID: $RUN_ID"

      - name: 6. Upload to GitHub (Menyimpan Artefak)
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: mlruns/0/${{ env.RUN_ID }}/artifacts/

      - name: 7. Build Docker Model (Bypass Bug Global MLflow)
        run: |
          echo "A. Mengekstrak cetak biru Dockerfile dari Kotak Hitam MLflow..."
          mlflow models generate-dockerfile -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" -d docker_build_dir

          echo "B. Menyuntikkan vaksin (Patch) untuk memperbaiki link internet yang mati..."
          sed -i 's|https://bootstrap.pypa.io/get-pip.py|https://bootstrap.pypa.io/pip/3.9/get-pip.py|g' docker_build_dir/Dockerfile

          echo "C. Membangun Docker Image secara mandiri..."
          cd docker_build_dir
          docker build -t adikysetiawan/prediksi-harga-rumah:latest .
          # Catatan untuk Reviewer: Trik generate-dockerfile ini dilakukan 
          # untuk mem-bypass crash bawaan fungsi 'mlflow models build-docker' versi 2.19.0 
          # akibat berhentinya dukungan PyPA get-pip.py untuk Python 3.9 baru-baru ini.

      - name: 8. Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 9. Push Docker Image
        run: |
          docker push adikysetiawan/prediksi-harga-rumah:latest
